### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by yash-fn** [EthraZa/BackupOps#1]
Your Image is a whopping 400mb and includes multiple technologies that not all users may utilize. Is there not perhaps a way you could divide your project into multiple tagged images, one for each backup solution, so that the image may be smaller? Or, for those users that may employ more than one solution, how about a base image that dynamically downloads whatever is required for the specific user? Otherwise, your application is very nice!

**Comment by EthraZa** [comment]
Not sure if that would do that much difference but I may try.

**Comment by yash-fn** [comment]
Actually never mind, I think its probably outside the scope of the project really. backupninja for example already packages multiple other backup utilities within it. Wouldn't really make sense to try and divide it. Keep it simple stupid and it works fine. Also docker only stores it once per all instances anyways, so its a one time hit.
